# Generated by Django 4.1.3 on 2022-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_alter_user_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='weekly_goal',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
