# Generated by Django 4.1.3 on 2022-12-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
        ('user_details', '0003_alter_user_details_weekly_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='name',
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
