# Generated by Django 4.1.3 on 2022-12-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_remove_user_details_name_user_details_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='user_id',
            new_name='user',
        ),
    ]
