# Generated by Django 4.1.3 on 2022-12-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_rename_user_id_user_details_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='user',
            new_name='user_id',
        ),
    ]
