# Generated by Django 4.1.3 on 2022-12-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0007_remove_user_details_id_alter_user_details_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='height',
            field=models.FloatField(),
        ),
    ]
