# Generated by Django 4.1.3 on 2022-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nutrient_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=False, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('protien', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sugar', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('polyunsaturated_fat', models.FloatField()),
                ('monounsaturated_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('cholestrol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('vitaminA', models.FloatField()),
                ('vitaminC', models.FloatField()),
                ('iron', models.FloatField()),
            ],
        ),
    ]
