# Generated by Django 4.1.3 on 2022-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_food_intake_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=False, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('total_calorie_gained', models.FloatField()),
            ],
        ),
    ]
