# Generated by Django 4.1.3 on 2022-12-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
        ('user_food_intake_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_food_intake_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='user_food_intake_detail',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user'),
            preserve_default=False,
        ),
    ]
