# Generated by Django 4.1.3 on 2022-12-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_foodcalories_quantity'),
        ('user_food_intake_details', '0002_remove_user_food_intake_detail_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_food_intake_detail',
            name='total_calorie_gained',
        ),
        migrations.AlterField(
            model_name='user_food_intake_detail',
            name='food_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodcalories'),
        ),
    ]
