# Generated by Django 4.1.3 on 2022-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_calorie_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=False, serialize=False, verbose_name='ID')),
                ('calorie_intake', models.FloatField()),
                ('goal_calorie', models.FloatField()),
                ('remaining_calorie', models.FloatField()),
                ('burned_calorie', models.FloatField()),
            ],
        ),
    ]
