# Generated by Django 4.1.3 on 2022-12-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_calorie_details', '0003_remove_user_calorie_detail_remaining_calorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_calorie_detail',
            name='calorie_intake',
            field=models.FloatField(),
        ),
    ]
