# Generated by Django 4.1.3 on 2022-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('quantity_gm', models.FloatField()),
                ('calorie', models.FloatField()),
            ],
        ),
    ]
