# Generated by Django 4.1.3 on 2022-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_foodcalories_calorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcalories',
            name='calorie',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
