# Generated by Django 4.1.3 on 2022-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodcalories_calorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcalories',
            name='calorie',
            field=models.FloatField(default='0'),
        ),
    ]
