# Generated by Django 4.1.3 on 2022-12-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='burned_cal_detail',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('exercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercisecal')),
            ],
        ),
    ]
